version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mono2micro-backend
    container_name: backend
    hostname: 'localhost'
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - SCRIPTS_ADDRESS=http://scripts:5002
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases

  scripts:
    build:
      context: ./scripts
    image: mono2micro-scripts
    container_name: scripts
    hostname: 'localhost'
    ports:
      - 5002:5002
    environment:
      - PORT=5002
      - CODEBASES_PATH=/codebases/
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases
      - './scripts/:/app'

  functionality_refactor:
    build:
      context: ./tools/functionality_refactor/src
    image: functionality_refactor
    container_name: functionality_refactor
    command: /app/web_service
    hostname: 'localhost'
    ports:
      - 5001:5001
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases

  frontend:
    build:
      context: ./frontend/
    image: mono2micro-frontend                                                     
    container_name: frontend
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 3000:3000
    stdin_open: true
    restart: unless-stopped
    volumes:
      - '/app/node_modules'
      - './frontend/:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
